### ISSUE TITLE
想问一下，用的缩放算法是什么？

### ISSUE THREAD

**Issue by soleige** [zhongyang219/WindowResizer#1]
最近用4K屏玩vallhalla的时候，发现这游戏只能720p窗口或者全屏显示，所以搜到了这个
想问下大佬，720p的窗口，缩放200%的时候，用的是什么算法呢？可以做到整数缩放吗

**Comment by zhongyang219** [comment]
其实很简单的，根本没用什么算法，使用的是Windows API函数SetWindowPos。
