### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by huigang39** [zhongyang219/WindowResizer#2]
请问一下，能不能添加一个“将窗口居中”的功能？

**Comment by setsumi** [comment]
https://github.com/setsumi/WindowResizer/releases

![image](https://user-images.githubusercontent.com/5970554/210457125-e78cc812-2114-4a29-ba65-a79319b5e447.png)

**Comment by huigang39** [comment]
> https://github.com/setsumi/WindowResizer/releases
> 
> ![image](https://user-images.githubusercontent.com/5970554/210457125-e78cc812-2114-4a29-ba65-a79319b5e447.png)

好的，感谢🤯
